# Generated by Django 5.2.13 on 2026-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], default='success', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('records_affected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
