# Generated by Django 5.2.13 on 2026-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_black_ink_reward', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
