# Generated by Django 5.2.13 on 2026-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0002_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('daily_login', 'Daily Login Reward'), ('ad_reward', 'Ad Reward'), ('quill_purchase', 'Quill Purchase'), ('chapter_unlock', 'Chapter Unlock'), ('author_payout', 'Author Payout'), ('admin_adjustment', 'Admin Adjustment'), ('admin_gift', 'Admin Gift')], max_length=20),
        ),
    ]
