# Generated by Django 5.2.13 on 2026-06-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0004_alter_book_cover_image_alter_book_free_chapters'),
        ('currencyApp', '0003_alter_transaction_transaction_type'),
        ('userApp', '0013_authorprofile_free_chapters_user_admin_agreed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingAuthorBonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=4, unique=True)),
            ],
            options={
                'verbose_name': 'Founding Author Bonus Tier',
                'verbose_name_plural': 'Founding Author Bonus Tiers',
                'ordering': ['-percent'],
            },
        ),
        migrations.CreateModel(
            name='FoundingAuthorDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('book_count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Founding Author Duration',
                'verbose_name_plural': 'Founding Author Durations',
                'ordering': ['book_count'],
            },
        ),
        migrations.CreateModel(
            name='FoundingAuthorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founding_author_slot', to='userApp.authorprofile')),
                ('bonus_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='currencyApp.foundingauthorbonustier')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='currencyApp.foundingauthorduration')),
            ],
            options={
                'verbose_name': 'Founding Author Slot',
                'verbose_name_plural': 'Founding Author Slots',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='FoundingAuthorEligibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founding_author_eligibility', to='booksApp.book')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_books', to='currencyApp.foundingauthorslot')),
            ],
            options={
                'verbose_name': 'Founding Author Eligible Book',
                'verbose_name_plural': 'Founding Author Eligible Books',
                'unique_together': {('slot', 'book')},
            },
        ),
    ]
