# Generated by Django 5.2.13 on 2026-06-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0004_foundingauthorbonustier_foundingauthorduration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundingauthorslot',
            options={'ordering': ['slot_number'], 'verbose_name': 'Founding Author Slot', 'verbose_name_plural': 'Founding Author Slots'},
        ),
        migrations.RenameField(
            model_name='foundingauthorslot',
            old_name='rank',
            new_name='slot_number',
        ),
    ]
