# Generated by Django 5.2.13 on 2026-06-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0005_alter_foundingauthorslot_options_and_more'),
        ('userApp', '0013_authorprofile_free_chapters_user_admin_agreed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundingauthorslot',
            name='author_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founding_author_slot', to='userApp.authorprofile'),
        ),
    ]
