# Generated by Django 5.2.13 on 2026-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0006_alter_foundingauthorslot_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyloginreward',
            name='current_streak_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
