# Generated by Django 5.2.13 on 2026-07-15 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0007_dailyloginreward_current_streak_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('currency_type', models.CharField(choices=[('black_ink', 'Black Ink Drop'), ('gold_ink', 'Gold Ink Drop'), ('quills', 'Quills')], default='black_ink', max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited redemptions.', null=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('daily_login', 'Daily Login Reward'), ('ad_reward', 'Ad Reward'), ('quill_purchase', 'Quill Purchase'), ('chapter_unlock', 'Chapter Unlock'), ('author_payout', 'Author Payout'), ('admin_adjustment', 'Admin Adjustment'), ('admin_gift', 'Admin Gift'), ('promo_code', 'Promo Code Redemption')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='currencyApp.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Redemption',
                'verbose_name_plural': 'Promo Code Redemptions',
                'ordering': ['-redeemed_at'],
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
