# Generated by Django 5.2.13 on 2026-07-22 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0008_promocode_alter_transaction_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quills', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('bonus_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Display only — the Quills bonus is already baked into the quills field.', max_digits=5, null=True)),
                ('total_value_cents', models.PositiveIntegerField(blank=True, help_text='Display only — the "value" shown on the purchase screen.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quill Bundle',
                'verbose_name_plural': 'Quill Bundles',
                'ordering': ['sort_order', 'quills'],
            },
        ),
        migrations.CreateModel(
            name='QuillPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_paid_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quill_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='currencyApp.quillbundle')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quill_purchase', to='currencyApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quill_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quill Purchase',
                'verbose_name_plural': 'Quill Purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
