# Generated by Django 5.2.13 on 2026-08-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0009_quillbundle_quillpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='referral_reward_amount',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('daily_login', 'Daily Login Reward'), ('ad_reward', 'Ad Reward'), ('quill_purchase', 'Quill Purchase'), ('chapter_unlock', 'Chapter Unlock'), ('author_payout', 'Author Payout'), ('admin_adjustment', 'Admin Adjustment'), ('admin_gift', 'Admin Gift'), ('promo_code', 'Promo Code Redemption'), ('referral_reward', 'Referral Reward')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_redemption', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Redemption',
                'verbose_name_plural': 'Referral Redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
