# Generated by Django 5.2.13 on 2026-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_pending_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
