# Generated by Django 5.2.13 on 2026-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_book_has_pending_changes_book_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='bookCovers/default.png', null=True, upload_to='bookCovers/'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='page_type',
            field=models.CharField(choices=[('prologue', 'Prologue'), ('authors_note', "Author's Note"), ('dedication', 'Dedication'), ('acknowledgements', 'Acknowledgements'), ('next_book_teaser', 'Next Book Teaser')], max_length=20),
        ),
    ]
