# Generated by Django 5.2.13 on 2026-05-27 15:08

import booksApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0003_alter_book_cover_image_alter_bookpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='bookCovers/default.png', null=True, upload_to=booksApp.models.book_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='free_chapters',
            field=models.IntegerField(default=10),
        ),
    ]
