# Generated by Django 5.2.13 on 2026-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0004_alter_book_cover_image_alter_book_free_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='auto_unlock_chapters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='auto_unlock_prompted',
            field=models.BooleanField(default=False),
        ),
    ]
