# Generated by Django 5.2.13 on 2026-07-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0005_userbook_auto_unlock_chapters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadingprogress',
            name='unlock_currency_type',
        ),
        migrations.AddField(
            model_name='userreadingprogress',
            name='black_ink_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreadingprogress',
            name='gold_ink_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreadingprogress',
            name='quills_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreadingprogress',
            name='unlocked_free',
            field=models.BooleanField(default=False),
        ),
    ]
