# Generated by Django 5.2.13 on 2026-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0006_remove_userreadingprogress_unlock_currency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
