# Generated by Django 5.2.13 on 2026-07-08 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('read', 'Read')], max_length=20)),
                ('date', models.DateField()),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='statsApp_da_user_id_2f4548_idx')],
                'unique_together': {('user', 'activity_type', 'date')},
            },
        ),
    ]
