# Generated by Django 5.2.13 on 2026-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='platform',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
