# Generated by Django 5.2.13 on 2026-07-08 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0003_dailyactivity_platform_event_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'activity_type', 'platform', 'date')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['platform'], name='statsApp_ev_platfor_a0edad_idx'),
        ),
    ]
