# Generated by Django 5.2.13 on 2026-04-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatars/admin/default.png', null=True, upload_to='avatars/admin/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatars/reader/default.png', null=True, upload_to='avatars/reader/'),
        ),
    ]
