# Generated by Django 5.2.13 on 2026-04-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_adminprofile_avatar_url_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('tier', models.IntegerField(default=1)),
                ('contract_link', models.URLField(blank=True, null=True)),
                ('avatar_url', models.ImageField(blank=True, default='avatars/author/default.png', null=True, upload_to='avatars/author/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
