# Generated by Django 5.2.13 on 2026-04-09 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_authorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('avatar_url', models.ImageField(blank=True, default='avatars/moderator/default.png', null=True, upload_to='avatars/moderator/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderators', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
