# Generated by Django 5.2.13 on 2026-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_moderatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='show_real_name',
            field=models.BooleanField(default=False),
        ),
    ]
