# Generated by Django 5.2.13 on 2026-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_authorprofile_first_name_authorprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='is_publicly_visible',
            field=models.BooleanField(default=False),
        ),
    ]
