# Generated by Django 5.2.13 on 2026-04-17 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_authorprofile_is_publicly_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_login_role',
            field=models.CharField(blank=True, choices=[('reader', 'Reader'), ('free_author', 'Free Author'), ('author', 'Author'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='reader', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new_author', 'New Author'), ('new_genre', 'New Genre'), ('tier_review', 'Tier Review'), ('contract_addendum', 'Contract Addendum'), ('leave_platform', 'Leave Platform'), ('rejoin_platform', 'Rejoin Platform')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('not_at_this_time', 'Not At This Time'), ('cleared', 'Cleared')], default='pending', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('genre_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('writing_sample_link', models.URLField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reader_notes', models.TextField(blank=True, null=True)),
                ('contact_attempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeAuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('show_real_name', models.BooleanField(default=False)),
                ('is_publicly_visible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.ImageField(blank=True, default='avatars/free_author/default.png', null=True, upload_to='avatars/free_author/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
