# Generated by Django 5.2.13 on 2026-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freeauthorprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
