# Generated by Django 5.2.13 on 2026-05-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_authorprofile_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='userApp.authorprofile')),
                ('free_author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='userApp.freeauthorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('author_profile__isnull', False)), fields=('user', 'author_profile'), name='unique_user_author_follow'), models.UniqueConstraint(condition=models.Q(('free_author_profile__isnull', False)), fields=('user', 'free_author_profile'), name='unique_user_free_author_follow')],
            },
        ),
    ]
