# Generated by Django 5.2.13 on 2026-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_authorprofile_free_chapters_user_admin_agreed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='is_founding_author',
            field=models.BooleanField(default=False),
        ),
    ]
