# Generated by Django 5.2.13 on 2026-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_authhandofftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reading_font_size',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sepia', 'Sepia'), ('amoled', 'AMOLED Black')], default='light', max_length=10),
        ),
    ]
