# Generated by Django 5.2.13 on 2026-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_userprofile_reading_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reading_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sepia', 'Sepia'), ('amoled', 'AMOLED Black')], default='dark', max_length=10),
        ),
    ]
