# Generated by Django 5.2.13 on 2026-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0017_alter_userprofile_reading_theme'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowauthor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_profile__isnull', False), ('free_author_profile__isnull', True)), models.Q(('author_profile__isnull', True), ('free_author_profile__isnull', False)), _connector='OR'), name='follow_exactly_one_author_type'),
        ),
    ]
